[repository]
name = "ploneconf2025"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "calver"
container_images_prefix = "ghcr.io/elcoda/ploneconf2025"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "ploneconf2025.core"
path = "backend"
code_path = "src/ploneconf2025/core"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "volto-ploneconf2025-core"
path = "frontend/packages/volto-ploneconf2025-core"
code_path = "src"
changelog = "frontend/packages/volto-ploneconf2025-core/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-ploneconf2025-core/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "8ffe75bb78ec0325afa837c962d114c1f6845ef2"
generated_date = "2025-10-14 07:34:43"
