---
cluster:
  hosts:
    ploneconf2025-elcoda.tangrama.com.br:
      ansible_user: root
      ansible_host: ploneconf2025-elcoda.tangrama.com.br
      host: ploneconf2025-elcoda
      hostname: ploneconf2025-elcoda.tangrama.com.br
      swarm_node:
        labels:
          type: manager
          env: production

  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            ploneconf2025-elcoda.tangrama.com.br:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
